name: 03-Workflow Runner

on:
    push:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Running OS
              run: echo "Running on ${{ runner.os }} operating system!"